description: Heat template for Centos 7 with BackupPC.
heat_template_version: '2018-03-02'
outputs:
  backuppc_private_ip:
    description: Private IP address of node
    value:
      get_attr:
      - node
      - first_address
parameters:
  flavor:
    default: Mini
    description: Specify the flavor of the instance.
    label: Flavor
    type: string
  image_name:
    default: Centos 7
    description: Name or ID of the image being used.
    type: string
  instance_name:
    description: Name of the instance.
    type: string
  instance_vol_size:
    default: 50
    description: Boot volume size for the instance.
    type: string
  internal_net:
    description: Internal network name or ID.
    type: string
  internal_subnet:
    description: Internal subnet name or ID.
    type: string
  key_name:
    description: Name of key-pair to be used for the ELK server.
    label: key_name
    type: string
  password:
    description: Specify domain name for nginx server (Example; blog.alefnode.com)
      to internet.
    type: password
resources:
  node:
    properties:
      admin_user: centos
      block_device_mapping:
      - delete_on_termination: false
        device_name: vda
        volume_id:
          get_resource: instance_volume
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      name:
        get_param: instance_name
      networks:
      - port:
          get_resource: backuppc_port
      user_data:
        str_replace:
          params:
            $PASSWORD:
              get_param: password
          template: |
            echo "Install BackupPC"

            sudo yum install epel-release wget -y
            sudo yum update -y
            sudo yum install backuppc nfs-utils libnfs-utils bzip2 -y
            sudo systemctl enable backuppc
            sudo systemctl enable httpd
            sudo systemctl restart backuppc

            echo "Add permissions to webserver"
            sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
            sudo firewall-cmd --reload

            echo "Edit BackupPC config files"
            sudo sed -i "s/{CgiAdminUserGroup} = ''/{CgiAdminUserGroup} = 'backuppc'/g" /etc/BackupPC/config.pl
            sudo sed -i "s/{PingPath} = ''/{PingPath} = '\/bin\/ping'/g" /etc/BackupPC/config.pl

            sudo sed -i "s/Require local/Require all granted/g" /etc/httpd/conf.d/BackupPC.conf

            htpasswd -b -c /etc/BackupPC/apache.users backuppc $PASSWORD

            systemctl restart backuppc.service
            systemctl restart httpd.service

            cd /var/lib/BackupPC/
            sudo -u backuppc ssh-keygen -f id_rsa -t rsa -N ''

    type: OS::Nova::Server
  backuppc_port:
    properties:
      fixed_ips:
      - subnet_id:
          get_param: internal_subnet
      network_id:
        get_param: internal_net
      security_groups:
      - get_resource: backuppc_security_group
    type: OS::Neutron::Port
  backuppc_security_group:
    properties:
      rules:
      - port_range_max: 80
        port_range_min: 80
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
    type: OS::Neutron::SecurityGroup
  instance_volume:
    properties:
      image:
        get_param: image_name
      name: backuppc_vol1
      size:
        get_param: instance_vol_size
    type: OS::Cinder::Volume
