description: Heat template for Centos 7 and HAProxy.
heat_template_version: 2018-03-02
parameters:
  key_name:
    type: string
    label: key_name
    description: Name of key-pair to be used for the HaProxy server.

  image_name:
        type: string
        description: Name or ID of the image being used.

  flavor:
    type: string
    label: Flavor
    description: Specify the flavor of the instance.
    default: Mini

  public_net:
    type: string
    description: Public network name or ID.

  internal_net:
    type: string
    description: Internal network name or ID.

  internal_subnet:
    type: string
    description: Internal subnet name or ID.

  instance_name:
    type: string
    description: Name of the instance.

  instance_vol_size:
    type: string
    default: 50
    description: Boot volume size for the instance.

  proxy_url:
    type: string
    description: Specify the proxy URL, if the server does not have direct access to internet.

resources:
  haproxy_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_param: internal_net }
          security_groups: [ get_resource: haproxy_security_group ]
          fixed_ips:
            - subnet_id: { get_param: internal_subnet }

  haproxy_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: haproxy_port }

  haproxy_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 1
          port_range_max: 65000

  instance_volume:
    type: OS::Cinder::Volume
    properties:
      name: haproxy_vol1
      size: { get_param: instance_vol_size }
      image: {get_param: image_name }

  haproxy:
        type: OS::Nova::Server
        properties:
          name: { get_param: instance_name }
          block_device_mapping:
          - device_name: vda
            volume_id: { get_resource: instance_volume }
            delete_on_termination: false
          key_name: { get_param: key_name }
          flavor: { get_param: flavor }
          admin_user: centos
          networks:
            - port: { get_resource: haproxy_port }
          user_data:
            str_replace:
              params:
                $PROXY: { get_param: proxy_url }
              template: |
                #!/bin/sh -v

                echo "Installing HAProxy"
                sudo yum install epel-release wget -y
                sudo yum update -y
                sudo yum install haproxy
                sudo systemctl enable haproxy

                echo "Create certificate to first use for letsencrypt"
                DOMAIN="test"

                # Generate a passphrase
                PASSPHRASE=$(head -c 500 /dev/urandom | tr -dc a-z0-9A-Z | head -c 16; echo)

                # Generate the server private key
                openssl genrsa -des3 -out $DOMAIN.key -passout pass:$PASSPHRASE 2048

                # Generate the CSR
                openssl req \
                    -new \
                    -batch \
                    -key $DOMAIN.key \
                    -out $DOMAIN.csr \
                    -passin pass:$PASSPHRASE
                cp $DOMAIN.key $DOMAIN.key.org

                # Strip the password so we don't have to type it every time we restart Apache
                openssl rsa -in $DOMAIN.key.org -out $DOMAIN.key -passin pass:$PASSPHRASE

                # Generate the cert
                openssl x509 -req -days 365 -in $DOMAIN.csr -signkey $DOMAIN.key -out $DOMAIN.crt
                cp $DOMAIN.crt /tmp/
                cp $DOMAIN.key /tmp/
                rm -rf $DOMAIN*

                sudo mkdir -p /etc/haproxy/certs/
                sudo -E bash -c "cat /tmp/$DOMAIN.crt /tmp/$DOMAIN.key > /etc/haproxy/certs/$DOMAIN.pem"
                sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
                sudo curl -o /etc/haproxy/haproxy.cfg https://raw.githubusercontent.com/alefnode/heat-templates/master/centos-haproxy/haproxy-template.cfg



outputs:
  haproxy_private_ip:
        description: Private IP address of haproxy
        value: { get_attr: [ haproxy, first_address ] }
  haproxy_public_ip:
        description: Floating IP address of haproxy
        value: { get_attr: [ haproxy_floating_ip, floating_ip_address ] }
